### ISSUE TITLE
Pwned passwords API doesn't need a key

### ISSUE THREAD

**Issue by GoodGuyGroves** [turbot/steampipe-plugin-hibp#9]
**Describe the bug**
The HIBP pwned passwords API does not require an API key but the HIBP plugin still requires one.
```
> select hash, count from hibp_password where plaintext = 'love';
Error: api key must be configured (SQLSTATE HV000)
```

**Steampipe version (`steampipe -v`)**
steampipe version 0.16.4

**Plugin version (`steampipe plugin list`)**
hub.steampipe.io/plugins/turbot/shodan@latest v0.4.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).
This simple query `select hash, count from hibp_password where plaintext = 'love';` should be able to execute just fine. To validate, you can follow [this gist here](https://gist.github.com/GoodGuyGroves/95db0d632c89ac9a389ad015b49b9701) to query the API from the command line without needing an API key.

**Expected behavior**
I expected a response to be returned. :)

**Comment by misraved** [comment]
Welcome to Steampipe @GoodGuyGroves 👍 and thanks for raising the issue 👍.

I have created a draft [PR](https://github.com/turbot/steampipe-plugin-hibp/pull/10) as a possible fix for this issue, however, I am not sure if this is the most optimal one.

@cbruno10 thoughts?
